doctrine:
  dbal:
    url: null
    server_version: '8'
    dbname: '%env(DATABASE_NAME)%'
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    driver: pdo_mysql
