nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        allow_private_network: false
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/': null

when@dev:
  nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: [ '*' ]
        allow_headers: [ '*' ]
        allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
        max_age: 3600
