when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
        register_error_handler: false # Disables the ErrorListener, ExceptionListener and FatalErrorListener integrations of the base PHP SDK
        tracing:
          enabled: false

    monolog:
        handlers:
            sentry:
                type: fingers_crossed
                action_level: error
                handler: sentry_main
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50
            sentry_main:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
