version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        APP_ENV: dev
        ALLOW_ORIGIN: http://localhost:5173
    environment:
      APP_ENV: dev
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: myapp
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      RABBITMQ_USER: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FE_APP_BASE_URL: http://localhost:5173
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/api
      - /var/www/api/vendor

  app:
    build:
      context: .
      dockerfile: Dockerfile.devapp
      args:
        APP_ENV: dev
    environment:
      APP_ENV: dev
      API_BASE_URL: http://127.0.0.1:8080/api/v1
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
      args:
        APP_ENV: dev
    environment:
      APP_ENV: dev
      DATABASE_NAME: myapp
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      RABBITMQ_USER: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./:/app

volumes:
  db_data:
