api_v1:
    resource:
        path: ../src/Controller/V1/
        namespace: App\Controller\V1
    type: attribute
    prefix: /api/v1/


api_v1_login:
    path: /api/v1/login

api_v1_refresh_token:
    path: /api/v1/token/refresh
