name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/smartfreelancer-consumer:${{ github.sha }}-${{ env.TIMESTAMP }} -f Dockerfile.consumer .
          docker push docker.pkg.github.com/${{ github.repository }}/smartfreelancer-consumer:${{ github.sha }}-${{ env.TIMESTAMP }}

      - name: Run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull docker.pkg.github.com/${{ github.repository }}/smartfreelancer-consumer:${{ github.sha }}-${{ env.TIMESTAMP }}
            docker run -d --name smartfreelancer-consumer-${{ github.sha }}-${{ env.TIMESTAMP }} \
              -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
              -e APP_ENV=prod \
              -e APP_DEBUG=0 \
              -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
              -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
              -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e SENTRY_DSN=${{ secrets.SENTRY_DSN_CONSUMER }} \
              -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
              -e RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }} \
              -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
              -e RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} \
              -e FE_BASE_URL=${{ secrets.FE_BASE_URL }} \
              -p $(shuf -i 12000-12999 -n 1):80 \
              docker.pkg.github.com/${{ github.repository }}/smartfreelancer-consumer:${{ github.sha }}-${{ env.TIMESTAMP }}

      - name: Adjust nginx and stop old container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -q --filter "name=smartfreelancer-consumer" | grep -v $(docker container ls -aqf name=smartfreelancer-consumer-${{ github.sha }}-${{ env.TIMESTAMP }}))
            docker rm $(docker ps -aq --filter "name=smartfreelancer-consumer" | grep -v $(docker container ls -aqf name=smartfreelancer-consumer-${{ github.sha }}-${{ env.TIMESTAMP }}))
            docker image prune --all --force

