# Docs for the Google Cloud Build action: https://github.com/marketplace/actions/google-cloud-build
# Docs for the Google App Engine Deploy action: https://github.com/marketplace/actions/deploy-to-google-app-engine
# More GitHub Actions for Google Cloud: https://github.com/marketplace?type=actions&query=google%20cloud

name: Build and deploy container app to Google App Engine - smartfreelancer-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/smartfreelancer-api:${{ github.sha }}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to Google App Engine
        uses: GoogleCloudPlatform/github-actions/app-engine-deploy@v1
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: ${{ github.sha }}
          image_url: ${{ env.IMAGE_NAME }}
