name: Publish API Docker image to GitHub registry

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/smartfreelancer-api:latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ env.IMAGE_NAME }}
