# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - smartfreelancer-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/smartfreelancer-api:${{ github.sha }}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        file: ./Dockerfile.api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'smartfreelancer-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5f60f96b52b48cb8e29e607257fc04a }}
        images: ${{ env.IMAGE_NAME }}
